{% set name = "teos10" %}
{% set version = "0.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/teos10-{{ version }}.tar.gz
  sha256: 391ab9c700617260d62980e500a313b970d3f8fbf3807cb2608ad4d08525c70d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - jax

test:
  imports:
    - teos10
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Unofficial Python implementation of the TEOS-10 properties of water
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/teos10

extra:
  recipe-maintainers:
    - mvdh7
